### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by codsec** [IgrutinovicL/TrovoViewbot#1]
![image](https://user-images.githubusercontent.com/44205014/135503787-065077da-2429-44ca-8140-01f7a88e2af5.png)

this error is probably because of the cookies, but the thing is, where should i put them exacly? or what is this error?

**Comment by IgrutinovicL** [comment]
the cookies have to be placed in a folder called "active_cookies" , but i do not suggest that you use the bot since it is against TOS.
