### ISSUE TITLE
Alternative to cookie monster?

### ISSUE THREAD

**Issue by mosheernser880** [IgrutinovicL/TrovoViewbot#10]
Is there a replacement for the Cookie-monster program?
I have an extension Cookiebro
https://chrome.google.com/webstore/detail/cookiebro/lpmockibcakojclnfmhchibmdpmollgn

**Comment by IgrutinovicL** [comment]
You can try to get a cookie with Cookiebro but I have not tested that. Does cookie monster still not work for you?

**Comment by mosheernser880** [comment]
yes doesn't work

**Comment by mosheernser880** [comment]
https://github.com/IgrutinovicL/Cookie-monster
according to the link that you indicated, it says that there is no file. Where to download, then?

**Comment by IgrutinovicL** [comment]
> https://github.com/IgrutinovicL/Cookie-monster according to the link that you indicated, it says that there is no file. Where to download, then?

I don't understand your question. You download the files by pressing the green code button and there should be a download zip option. Then you run cookie monster with python

**Comment by mosheernser880** [comment]
I want to know how run cookie monster with python?😞

**Comment by mosheernser880** [comment]
maybe just add the ability to enter a username and password from the account?

**Comment by IgrutinovicL** [comment]
We can get into a discord call tomorrow so i can show you. XIII#1573

**Comment by mosheernser880** [comment]
ModuleNotFoundError: No module named 'undetected_chromedriver'

**Comment by IgrutinovicL** [comment]
Try to comment out the line where it says freeze_support()

**Comment by mosheernser880** [comment]
how to do it?

**Comment by IgrutinovicL** [comment]
Put a # in front of freeze_support()

Like so:

`#freeze_support()`

If you don't know how to comment a line in Python I don't believe I can help you much.

**Comment by mosheernser880** [comment]
I can throw off trovo accounts.
Make me cookie files

**Comment by mosheernser880** [comment]
wrote to discord

**Comment by mosheernser880** [comment]
thanks, everything worked
