### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by mosheernser880** [IgrutinovicL/TrovoViewbot#9]
Can you provide clear instructions on how to get started?e.g [Cookie-monster](https://github.com/IgrutinovicL/Cookie-monster) doesn't work

**Comment by IgrutinovicL** [comment]
1. Get some cookies with Cookie-monster
2. Before starting the bot place the cookies in the active_cookies directory
3. Make sure that you are using the latest chrome that undetected-chromedriver supports. 
4. Start the bot and enter the setup mode.
5. Do not choose more bots than the number of cookies you have.
6. Answer the questions in the setup.
7. After that select start when starting the bot.

Can you tell me what does the bot/cookie-monster say when you try to run it? What error comes up?
